(function(d,h,j){var k={version:"2.0.1",tipLocation:"bottom",nubPosition:"auto",scrollSpeed:300,timer:0,startTimerOnClick:!0,startOffset:0,nextButton:!0,tipAnimation:"fade",pauseAfter:[],tipAnimationFadeSpeed:300,cookieMonster:!1,cookieName:"joyride",cookieDomain:!1,tipContainer:"body",postRideCallback:d.noop,postStepCallback:d.noop,template:{link:'<a href="#close" class="joyride-close-tip">X</a>',timer:'<div class="joyride-timer-indicator-wrap"><span class="joyride-timer-indicator"></span></div>',
tip:'<div class="joyride-tip-guide"><span class="joyride-nub"></span></div>',wrapper:'<div class="joyride-content-wrapper"></div>',button:'<a href="#" class="small button joyride-next-tip"></a>'}},i=i||!1,a={},b={init:function(c){return this.each(function(){if(d.isEmptyObject(a)){a=d.extend(k,c);a.document=h.document;a.$document=d(a.document);a.$window=d(h);a.$content_el=d(this);a.body_offset=d(a.tipContainer).position();a.$tip_content=d("> li",a.$content_el);a.paused=!1;a.attempts=0;a.tipLocationPatterns=
{top:["bottom"],bottom:[],left:["right","top","bottom"],right:["left","top","bottom"]};b.jquery_check();if(!d.isFunction(d.cookie))a.cookieMonster=!1;if(!a.cookieMonster||!d.cookie(a.cookieName))a.$tip_content.each(function(a){b.create({$li:d(this),index:a})}),!a.startTimerOnClick&&a.timer>0?(b.show("init"),b.startTimer()):b.show("init");a.$document.on("click.joyride",".joyride-next-tip, .joyride-modal-bg",function(c){c.preventDefault();a.$li.next().length<1?b.end():a.timer>0?(clearTimeout(a.automate),
b.hide(),b.show(),b.startTimer()):(b.hide(),b.show())});a.$document.on("click.joyride",".joyride-close-tip",function(a){a.preventDefault();b.end()});a.$window.bind("resize.joyride",function(){b.is_phone()?b.pos_phone():b.pos_default()})}else b.restart()})},resume:function(){b.set_li();b.show()},tip_template:function(c){var e,f;c.tip_class=c.tip_class||"";e=d(a.template.tip).addClass(c.tip_class);f=d.trim(d(c.li).html())+b.button_text(c.button_text)+a.template.link+b.timer_instance(c.index);e.append(d(a.template.wrapper));
e.first().attr("data-index",c.index);d(".joyride-content-wrapper",e).append(f);return e[0]},timer_instance:function(c){return c===0&&a.startTimerOnClick&&a.timer>0||a.timer===0?"":b.outerHTML(d(a.template.timer)[0])},button_text:function(c){a.nextButton?(c=d.trim(c)||"Next",c=b.outerHTML(d(a.template.button).append(c)[0])):c="";return c},create:function(c){var e=c.$li.attr("data-button")||c.$li.attr("data-text"),f=c.$li.attr("class"),c=d(b.tip_template({tip_class:f,index:c.index,button_text:e,li:c.$li}));
d(a.tipContainer).append(c)},show:function(c){var e={},f=[],g=0,f=null;if(a.$li===j||d.inArray(a.$li.index(),a.pauseAfter)===-1)if(a.paused?a.paused=!1:b.set_li(c),a.attempts=0,a.$li.length&&a.$target.length>0){f=(a.$li.data("options")||":").split(";");g=f.length;for(c=g-1;c>=0;c--)g=f[c].split(":"),g.length===2&&(e[d.trim(g[0])]=d.trim(g[1]));a.tipSettings=d.extend({},a,e);a.tipSettings.tipLocationPattern=a.tipLocationPatterns[a.tipSettings.tipLocation];/body/i.test(a.$target.selector)||b.scroll_to();
b.is_phone()?b.pos_phone(!0):b.pos_default(!0);f=d(".joyride-timer-indicator",a.$next_tip);/pop/i.test(a.tipAnimation)?(f.outerWidth(0),a.timer>0?(a.$next_tip.show(),f.animate({width:d(".joyride-timer-indicator-wrap",a.$next_tip).outerWidth()},a.timer)):a.$next_tip.show()):/fade/i.test(a.tipAnimation)&&(f.outerWidth(0),a.timer>0?(a.$next_tip.fadeIn(a.tipAnimationFadeSpeed),a.$next_tip.show(),f.animate({width:d(".joyride-timer-indicator-wrap",a.$next_tip).outerWidth()},a.timer)):a.$next_tip.fadeIn(a.tipAnimationFadeSpeed));
a.$current_tip=a.$next_tip}else a.$li&&a.$target.length<1?b.show():b.end();else a.paused=!0},is_phone:function(){return i?i.mq("only screen and (max-width: 767px)"):a.$window.width()<767?!0:!1},hide:function(){a.postStepCallback(a.$li.index(),a.$current_tip);d(".joyride-modal-bg").hide();a.$current_tip.hide()},set_li:function(c){c?(a.$li=a.$tip_content.eq(a.startOffset),b.set_next_tip(),a.$current_tip=a.$next_tip):(a.$li=a.$li.next(),b.set_next_tip());b.set_target()},set_next_tip:function(){a.$next_tip=
d(".joyride-tip-guide[data-index="+a.$li.index()+"]")},set_target:function(){var c=a.$li.attr("data-class"),b=a.$li.attr("data-id");a.$target=b?d(a.document.getElementById(b)):c?d("."+c).first():d("body")},scroll_to:function(){var c;c=a.$window.height()/2;c=Math.ceil(a.$target.offset().top-c+a.$next_tip.outerHeight());d("html, body").stop().animate({scrollTop:c},a.scrollSpeed)},paused:function(){return d.inArray(a.$li.index()+1,a.pauseAfter)===-1?!0:!1},destroy:function(){a.$document.off(".joyride");
d(h).off(".joyride");d(".joyride-close-tip, .joyride-next-tip, .joyride-modal-bg").off(".joyride");d(".joyride-tip-guide, .joyride-modal-bg").remove();clearTimeout(a.automate);a={}},restart:function(){b.hide();a.$li=j;b.show("init")},pos_default:function(c){Math.ceil(a.$window.height()/2);a.$next_tip.offset();var e=d(".joyride-nub",a.$next_tip),f=Math.ceil(e.outerHeight()/2);if(c=c||!1)a.$next_tip.css("visibility","hidden"),a.$next_tip.show();if(/body/i.test(a.$target.selector))a.$li.length&&b.pos_modal(e);
else if(b.bottom()?(a.$next_tip.css({top:a.$target.offset().top+f+a.$target.outerHeight(),left:a.$target.offset().left}),b.nub_position(e,a.tipSettings.nubPosition,"top")):b.top()?(a.$next_tip.css({top:a.$target.offset().top-a.$next_tip.outerHeight()-f,left:a.$target.offset().left}),b.nub_position(e,a.tipSettings.nubPosition,"bottom")):b.right()?(a.$next_tip.css({top:a.$target.offset().top,left:a.$target.outerWidth()+a.$target.offset().left}),b.nub_position(e,a.tipSettings.nubPosition,"left")):b.left()&&
(a.$next_tip.css({top:a.$target.offset().top,left:a.$target.offset().left-a.$next_tip.outerWidth()-f}),b.nub_position(e,a.tipSettings.nubPosition,"right")),!b.visible(b.corners(a.$next_tip))&&a.attempts<a.tipSettings.tipLocationPattern.length)e.removeClass("bottom").removeClass("top").removeClass("right").removeClass("left"),a.tipSettings.tipLocation=a.tipSettings.tipLocationPattern[a.attempts],a.attempts++,b.pos_default(!0);c&&(a.$next_tip.hide(),a.$next_tip.css("visibility","visible"))},pos_phone:function(c){var e=
a.$next_tip.outerHeight();a.$next_tip.offset();var f=a.$target.outerHeight(),g=d(".joyride-nub",a.$next_tip),h=Math.ceil(g.outerHeight()/2),c=c||!1;g.removeClass("bottom").removeClass("top").removeClass("right").removeClass("left");c&&(a.$next_tip.css("visibility","hidden"),a.$next_tip.show());/body/i.test(a.$target.selector)?a.$li.length&&b.pos_modal(g):b.top()?(a.$next_tip.offset({top:a.$target.offset().top-e-h}),g.addClass("bottom")):(a.$next_tip.offset({top:a.$target.offset().top+f+h}),g.addClass("top"));
c&&(a.$next_tip.hide(),a.$next_tip.css("visibility","visible"))},pos_modal:function(c){b.center();c.hide();d(".joyride-modal-bg").length<1&&d("body").append('<div class="joyride-modal-bg">').show();/pop/i.test(a.tipAnimation)?d(".joyride-modal-bg").show():d(".joyride-modal-bg").fadeIn(a.tipAnimationFadeSpeed)},center:function(){var c=a.$window;a.$next_tip.css({top:(c.height()-a.$next_tip.outerHeight())/2+c.scrollTop(),left:(c.width()-a.$next_tip.outerWidth())/2+c.scrollLeft()});return!0},bottom:function(){return/bottom/i.test(a.tipSettings.tipLocation)},
top:function(){return/top/i.test(a.tipSettings.tipLocation)},right:function(){return/right/i.test(a.tipSettings.tipLocation)},left:function(){return/left/i.test(a.tipSettings.tipLocation)},corners:function(c){var b=a.$window,d=b.width()+b.scrollLeft(),g=b.width()+b.scrollTop();return[c.offset().top<=b.scrollTop(),d<=c.offset().left+c.outerWidth(),g<=c.offset().top+c.outerHeight(),b.scrollLeft()>=c.offset().left]},visible:function(a){for(var b=a.length;b--;)if(a[b])return!1;return!0},nub_position:function(a,
b,d){b==="auto"?a.addClass(d):a.addClass(b)},startTimer:function(){a.$li.length?a.automate=setTimeout(function(){b.hide();b.show();b.startTimer()},a.timer):clearTimeout(a.automate)},end:function(){a.cookieMonster&&d.cookie(a.cookieName,"ridden",{expires:365,domain:a.cookieDomain});a.timer>0&&clearTimeout(a.automate);d(".joyride-modal-bg").hide();a.$current_tip.hide();a.postStepCallback(a.$li.index(),a.$current_tip);a.postRideCallback(a.$li.index(),a.$current_tip)},jquery_check:function(){return!d.isFunction(d.fn.on)?
(d.fn.on=function(a,b,d){return this.delegate(b,a,d)},d.fn.off=function(a,b,d){return this.undelegate(b,a,d)},!1):!0},outerHTML:function(a){return a.outerHTML||(new XMLSerializer).serializeToString(a)},version:function(){return a.version}};d.fn.joyride=function(a){if(b[a])return b[a].apply(this,Array.prototype.slice.call(arguments,1));else if(typeof a==="object"||!a)return b.init.apply(this,arguments);else d.error("Method "+a+" does not exist on jQuery.joyride")}})(jQuery,this);
